// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20251024195739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = "1",
                            Name = "Avocado",
                            Notes = "ripe",
                            RecipeId = 1,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 2,
                            Amount = "2",
                            Name = "Eggs",
                            Notes = "free-range",
                            RecipeId = 1,
                            Unit = "large"
                        },
                        new
                        {
                            Id = 3,
                            Amount = "1/2",
                            Name = "Cherry tomatoes",
                            Notes = "halved",
                            RecipeId = 1,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 4,
                            Amount = "2",
                            Name = "Whole grain bread",
                            Notes = "toasted",
                            RecipeId = 1,
                            Unit = "slices"
                        },
                        new
                        {
                            Id = 5,
                            Amount = "1",
                            Name = "Olive oil",
                            Notes = "extra virgin",
                            RecipeId = 1,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 6,
                            Amount = "1/4",
                            Name = "Salt",
                            Notes = "to taste",
                            RecipeId = 1,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 7,
                            Amount = "1/4",
                            Name = "Black pepper",
                            Notes = "freshly ground",
                            RecipeId = 1,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 8,
                            Amount = "1",
                            Name = "Quinoa",
                            Notes = "uncooked",
                            RecipeId = 2,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 9,
                            Amount = "2",
                            Name = "Baby spinach",
                            Notes = "fresh",
                            RecipeId = 2,
                            Unit = "cups"
                        },
                        new
                        {
                            Id = 10,
                            Amount = "1",
                            Name = "Cherry tomatoes",
                            Notes = "halved",
                            RecipeId = 2,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 11,
                            Amount = "1",
                            Name = "Cucumber",
                            Notes = "diced",
                            RecipeId = 2,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 12,
                            Amount = "1",
                            Name = "Red bell pepper",
                            Notes = "diced",
                            RecipeId = 2,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 13,
                            Amount = "1/4",
                            Name = "Red onion",
                            Notes = "thinly sliced",
                            RecipeId = 2,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 14,
                            Amount = "2",
                            Name = "Lemon juice",
                            Notes = "fresh",
                            RecipeId = 2,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 15,
                            Amount = "3",
                            Name = "Olive oil",
                            Notes = "extra virgin",
                            RecipeId = 2,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 16,
                            Amount = "1/2",
                            Name = "Salt",
                            Notes = "to taste",
                            RecipeId = 2,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 17,
                            Amount = "1/4",
                            Name = "Black pepper",
                            Notes = "freshly ground",
                            RecipeId = 2,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 18,
                            Amount = "2",
                            Name = "Salmon fillets",
                            Notes = "skin-on",
                            RecipeId = 3,
                            Unit = "6-oz"
                        },
                        new
                        {
                            Id = 19,
                            Amount = "1",
                            Name = "Broccoli",
                            Notes = "cut into florets",
                            RecipeId = 3,
                            Unit = "head"
                        },
                        new
                        {
                            Id = 20,
                            Amount = "2",
                            Name = "Carrots",
                            Notes = "cut into sticks",
                            RecipeId = 3,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 21,
                            Amount = "1",
                            Name = "Zucchini",
                            Notes = "sliced",
                            RecipeId = 3,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 22,
                            Amount = "3",
                            Name = "Olive oil",
                            Notes = "divided",
                            RecipeId = 3,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 23,
                            Amount = "2",
                            Name = "Garlic",
                            Notes = "minced",
                            RecipeId = 3,
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = 24,
                            Amount = "1",
                            Name = "Lemon",
                            Notes = "juiced",
                            RecipeId = 3,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 25,
                            Amount = "2",
                            Name = "Dill",
                            Notes = "fresh, chopped",
                            RecipeId = 3,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 26,
                            Amount = "1",
                            Name = "Salt",
                            Notes = "divided",
                            RecipeId = 3,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 27,
                            Amount = "1/2",
                            Name = "Black pepper",
                            Notes = "freshly ground",
                            RecipeId = 3,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 28,
                            Amount = "1",
                            Name = "Mixed berries",
                            Notes = "frozen",
                            RecipeId = 4,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 29,
                            Amount = "1/2",
                            Name = "Greek yogurt",
                            Notes = "plain, non-fat",
                            RecipeId = 4,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 30,
                            Amount = "1/2",
                            Name = "Banana",
                            Notes = "frozen",
                            RecipeId = 4,
                            Unit = "medium"
                        },
                        new
                        {
                            Id = 31,
                            Amount = "1/2",
                            Name = "Almond milk",
                            Notes = "unsweetened",
                            RecipeId = 4,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 32,
                            Amount = "1",
                            Name = "Protein powder",
                            Notes = "vanilla",
                            RecipeId = 4,
                            Unit = "scoop"
                        },
                        new
                        {
                            Id = 33,
                            Amount = "1",
                            Name = "Honey",
                            Notes = "optional",
                            RecipeId = 4,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 34,
                            Amount = "1",
                            Name = "Chia seeds",
                            Notes = "optional",
                            RecipeId = 4,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 35,
                            Amount = "1",
                            Name = "Chickpeas",
                            Notes = "15 oz, drained and rinsed",
                            RecipeId = 5,
                            Unit = "can"
                        },
                        new
                        {
                            Id = 36,
                            Amount = "1",
                            Name = "Quinoa",
                            Notes = "uncooked",
                            RecipeId = 5,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 37,
                            Amount = "1",
                            Name = "Sweet potato",
                            Notes = "cubed",
                            RecipeId = 5,
                            Unit = "large"
                        },
                        new
                        {
                            Id = 38,
                            Amount = "2",
                            Name = "Kale",
                            Notes = "chopped",
                            RecipeId = 5,
                            Unit = "cups"
                        },
                        new
                        {
                            Id = 39,
                            Amount = "1",
                            Name = "Red cabbage",
                            Notes = "shredded",
                            RecipeId = 5,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 40,
                            Amount = "2",
                            Name = "Tahini",
                            Notes = "raw",
                            RecipeId = 5,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 41,
                            Amount = "2",
                            Name = "Lemon juice",
                            Notes = "fresh",
                            RecipeId = 5,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 42,
                            Amount = "3",
                            Name = "Olive oil",
                            Notes = "divided",
                            RecipeId = 5,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 43,
                            Amount = "1",
                            Name = "Cumin",
                            Notes = "ground",
                            RecipeId = 5,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 44,
                            Amount = "1",
                            Name = "Salt",
                            Notes = "divided",
                            RecipeId = 5,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 45,
                            Amount = "1/2",
                            Name = "Black pepper",
                            Notes = "freshly ground",
                            RecipeId = 5,
                            Unit = "tsp"
                        });
                });

            modelBuilder.Entity("API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 320,
                            Category = "breakfast",
                            CookTimeMinutes = 5,
                            Description = "A nutritious and delicious breakfast bowl featuring creamy avocado, perfectly cooked eggs, and fresh tomatoes.",
                            Difficulty = "Easy",
                            Image = "🥑",
                            Instructions = "",
                            PrepTimeMinutes = 5,
                            Servings = 1,
                            Tags = "vegetarian,quick,healthy",
                            Title = "Avocado Toast Bowl"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 280,
                            Category = "lunch",
                            CookTimeMinutes = 15,
                            Description = "A protein-packed salad with quinoa, fresh vegetables, and a tangy dressing that's perfect for lunch or dinner.",
                            Difficulty = "Easy",
                            Image = "🥗",
                            Instructions = "",
                            PrepTimeMinutes = 10,
                            Servings = 2,
                            Tags = "vegan,gluten-free,high-protein",
                            Title = "Quinoa Power Salad"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 420,
                            Category = "dinner",
                            CookTimeMinutes = 20,
                            Description = "Perfectly grilled salmon fillets served with roasted seasonal vegetables for a healthy and satisfying dinner.",
                            Difficulty = "Medium",
                            Image = "🐟",
                            Instructions = "",
                            PrepTimeMinutes = 10,
                            Servings = 2,
                            Tags = "low-carb,high-protein,omega-3",
                            Title = "Grilled Salmon & Veggies"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 250,
                            Category = "breakfast",
                            CookTimeMinutes = 0,
                            Description = "A refreshing and nutritious smoothie packed with antioxidants, protein, and natural sweetness.",
                            Difficulty = "Easy",
                            Image = "🫐",
                            Instructions = "",
                            PrepTimeMinutes = 5,
                            Servings = 1,
                            Tags = "vegetarian,quick,antioxidants",
                            Title = "Berry Protein Smoothie"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 380,
                            Category = "lunch",
                            CookTimeMinutes = 25,
                            Description = "A nourishing bowl filled with roasted chickpeas, quinoa, and fresh vegetables topped with a creamy tahini dressing.",
                            Difficulty = "Medium",
                            Image = "🥙",
                            Instructions = "",
                            PrepTimeMinutes = 15,
                            Servings = 2,
                            Tags = "vegan,high-fiber,plant-based",
                            Title = "Chickpea Buddha Bowl"
                        });
                });

            modelBuilder.Entity("API.Models.Ingredient", b =>
                {
                    b.HasOne("API.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
